In [7]:
from sentence_transformers import SentenceTransformer
import tensorflow as tf

# Cargar el modelo preentrenado para generar embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')  # Puedes elegir otro modelo según tus necesidades

# Lista de frases para convertir a embeddings
frases = [
    "La inteligencia artificial está transformando el mundo.",
    "El aprendizaje profundo es una técnica clave en el procesamiento de lenguaje natural.",
    "¿Cómo se generan los embeddings?",
    "en que consisten los embeddings y lod transformers",
    "La inteligencia artificial es una tecnica transformadora"
]

# Generar embeddings para las frases
embeddings = model.encode(frases)

# Mostrar los resultados
for i, frase in enumerate(frases):
    print(f"Frase: {frase}")
    print(f"Embedding: {embeddings[i][:5]}...")  # Mostrar solo los primeros valores del embedding
    print()


C:\Users\tomas\ML\deep\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm



Frase: La inteligencia artificial está transformando el mundo.
Embedding: [-0.04948272  0.05770752 -0.00050072 -0.05088018 -0.00792877]...

Frase: El aprendizaje profundo es una técnica clave en el procesamiento de lenguaje natural.
Embedding: [ 0.01676631  0.02484792 -0.05824441 -0.01149719 -0.06505692]...

Frase: ¿Cómo se generan los embeddings?
Embedding: [ 0.00969372 -0.09212597  0.01370841  0.00419837  0.00237616]...

Frase: en que consisten los embeddings y lod transformers
Embedding: [-0.07904124 -0.04865225  0.00054112 -0.08442471  0.01466048]...

Frase: La inteligencia artificial es una tecnica transformadora
Embedding: [-0.0835342   0.01540011 -0.057212   -0.07926246 -0.05903137]...



In [8]:
embeddings[2]

array([ 9.69372317e-03, -9.21259746e-02,  1.37084080e-02,  4.19836957e-03,
        2.37616268e-03,  6.95533156e-02, -2.50207819e-02, -1.87175926e-02,
        3.62586789e-02, -5.01222946e-02,  5.18756807e-02, -1.69165898e-02,
        4.76766983e-03,  3.06400303e-02,  1.94672979e-02,  4.29092944e-02,
       -1.19530093e-02,  5.73895462e-02, -8.13359302e-03,  4.25100736e-02,
        5.53366020e-02,  1.44909350e-02, -2.78168861e-02,  3.14365141e-02,
        1.65497288e-02, -6.91203624e-02, -4.26088367e-03,  5.03181070e-02,
        5.42864092e-02, -9.79611576e-02,  2.25144401e-02,  3.96615677e-02,
       -6.01640670e-03,  5.00718914e-02,  5.86461974e-03,  5.95497340e-02,
        3.59098874e-02, -3.22040319e-02, -6.50166571e-02,  1.94177800e-03,
       -6.80586696e-02,  5.99150360e-02, -1.27734104e-02,  1.86579209e-02,
        3.96977998e-02, -1.14578307e-01, -3.15461755e-02,  5.40043926e-04,
       -8.87479633e-02, -1.08315069e-02, -9.27379206e-02, -5.06190099e-02,
       -3.71532664e-02,  

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
similitudes = cosine_similarity(embeddings)
# Mostrar los resultados
print("Matriz de similitud del coseno:")
print(similitudes)

# Interpretar similitudes para pares específicos
print("\nSimilitud entre la frase 1 y 2:", similitudes[0][1])
print("Similitud entre la frase 1 y 5:", similitudes[0][4])
print("Similitud entre la frase 2 y 5:", similitudes[1][4])
print("Similitud entre la frase 3 y 4:", similitudes[2][3])

Matriz de similitud del coseno:
[[1.0000001  0.47234815 0.38231775 0.39474615 0.80503994]
 [0.47234815 0.99999964 0.40248802 0.25172287 0.44661933]
 [0.38231775 0.40248802 1.0000002  0.6916104  0.31252074]
 [0.39474615 0.25172287 0.6916104  1.0000004  0.43628487]
 [0.80503994 0.44661933 0.31252074 0.43628487 1.0000005 ]]

Similitud entre la frase 1 y 2: 0.47234815
Similitud entre la frase 1 y 5: 0.80503994
Similitud entre la frase 2 y 5: 0.44661933
Similitud entre la frase 3 y 4: 0.6916104


In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
import numpy as np

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tomas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
path='C:\\Users\\tomas\ML\\env1\\data\\reviews_filmaffinity.csv'
df2 = pd.read_table(path, sep='\|\|', header=0, engine='python')
df2.sample(5)

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\|'
<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\|'
C:\Users\tomas\AppData\Local\Temp\ipykernel_26016\2050642239.py:1: SyntaxWarning: invalid escape sequence '\M'
  path='C:\\Users\\tomas\ML\\env1\\data\\reviews_filmaffinity.csv'
C:\Users\tomas\AppData\Local\Temp\ipykernel_26016\2050642239.py:2: SyntaxWarning: invalid escape sequence '\|'
  df2 = pd.read_table(path, sep='\|\|', header=0, engine='python')


film_name      gender film_avg_rate  review_rate  \
8471                  La isla mínima  Cine negro           7,2          6.0   
8192                  La isla mínima  Cine negro           7,2          8.0   
347            Ocho apellidos vascos     Comedia           6,0          5.0   
4124                       Celda 211    Thriller           7,7          9.0   
1601  Torrente 2: Misión en Marbella     Comedia           5,3          5.0   

                                           review_title  \
8471                             Sé lo que hicisteis...   
8192  A vista de pájaro: los escollos de extirpar la...   
347                               COMEDIA DECEPCIONANTE   
4124               Escalofriante en todos los sentidos.   
1601                            Tolerable segunda parte   

                                            review_text  
8471  La isla mínima es un thriller policíaco ambien...  
8192  Dar con el tono adecuado es siempre lo más dif...  
347   Cinta con demasiada crítica positiva antes de ...  
4124  Hay algo más allá de las rejas de “Celda 211”,...  
1601  Simpática secuela del taquillazo Torrente, en ...

In [6]:
df3=df2[df2['film_name']=='Tadeo Jones 2']
df3.count()

film_name        36
gender           36
film_avg_rate    36
review_rate      36
review_title     36
review_text      36
dtype: int64

In [15]:
df3['review_text'].tolist()

['"¿Qué es eso que me llama este señor de gitanilla?" Momia.Con cinco años desde la primera entrega, "Las aventuras de Tadeo Jones", Enrique Gato nos trae de nuevo al albañil arqueólogo en una de sus aventuras infantiles. Para analizar una película como "Tadeo Jones 2: El tesoro del Rey Midas" no puede limitarse uno a un análisis intrínseco: esta película es española, y como tal ha tenido más dificultades para existir que una película nacida en Pixar, DreamWorks o cualquier compañía similar.La historia nos devuelve a la mayoría de los personajes de la primera entrega, a excepción del vendedor ambulante a quien ponía voz José Mota. Un taxista andaluz ha sido la elección para sustituirlo.El resto todos siguen como estaban, no es una película que vaya a destacar especialmente por su desarrollo de personajes: Tadeo y Sara siguen como en la anterior con ese pequeña subtrama romántica a la que se nota que quieren dar más calado, la incorporación del taxista es acertada y hay un descubrimient

In [16]:
embeddingsTAdeo = model.encode(df3['review_text'].tolist())

In [28]:
df3['review_text'][3237]

'l simpático aventurero de producción española da un salto de calidad con una secuela que mejora sustancialmente la primera parte a nivel visual, con una animación más elaborada y detallada, y que también ofrece una historia mucho más divertida y con mejor ritmo en localizaciones tanto exóticas como cercanas.A todo esto hay que sumarle el cambio de secundario chistoso, que esta vez recae en el personaje de "La Momia", quien da más juego y tiene más gracia que su predecesor. En definitiva, el director Enrique Gato y su equipo demuestran que aún tienen mucho que contar sobre este aprendiz de arqueólogo y que son capaces de seguir mejorando en el modo de hacerlo. Más mini críticas en cinedepatio.com'

In [29]:
embeddingsTAdeo[1]

array([ 2.08656508e-02,  1.76260974e-02, -1.99322086e-02, -3.15782689e-02,
       -2.67101638e-02, -5.36235934e-03,  4.86004427e-02,  6.34679124e-02,
        1.86382346e-02,  6.33155778e-02,  1.27927512e-01, -8.27723816e-02,
        2.65719891e-02, -1.76671706e-02,  1.54092759e-02, -9.81137995e-03,
        5.64836860e-02,  2.71039847e-02,  5.65599464e-03,  2.63696834e-02,
        1.09973341e-01, -1.17674850e-01, -2.01914869e-02,  6.47431165e-02,
       -9.78938267e-02,  5.15736267e-02,  1.30423177e-02,  1.36492075e-02,
       -1.22715525e-01, -8.97513926e-02, -5.74698634e-02,  1.74350236e-02,
        7.63321593e-02, -2.29309648e-02, -2.57971529e-02,  5.02237119e-02,
       -4.36911965e-03, -3.96816581e-02, -3.61933894e-02,  7.41332397e-02,
       -9.12410766e-02,  4.87461723e-02, -7.59974271e-02, -4.61738110e-02,
       -1.66563727e-02, -8.77921134e-02,  7.26263374e-02,  2.07646228e-02,
       -3.95855345e-02, -2.94244867e-02, -9.01828706e-02, -5.48267998e-02,
       -6.11940548e-02, -