In [21]:
from sentence_transformers import SentenceTransformer
import tensorflow as tf

# Cargar el modelo preentrenado para generar embeddings
model = SentenceTransformer('all-MiniLM-L6-v2')  # Puedes elegir otro modelo según tus necesidades

# Lista de frases para convertir a embeddings
frases = [
    "La inteligencia artificial está transformando el mundo.",
    "El aprendizaje profundo es una técnica clave en el procesamiento de lenguaje natural.",
    "¿Cómo se generan los embeddings?",
    "en que consisten los embeddings y lod transformers",
    "La inteligencia artificial es una tecnica transformadora"
]

# Generar embeddings para las frases
embeddings = model.encode(frases)

# Mostrar los resultados
for i, frase in enumerate(frases):
    print(f"Frase: {frase}")
    print(f"Embedding: {embeddings[i][:5]}...")  # Mostrar solo los primeros valores del embedding
    print()


Frase: La inteligencia artificial está transformando el mundo.
Embedding: [-0.04948272  0.05770752 -0.00050072 -0.05088018 -0.00792877]...

Frase: El aprendizaje profundo es una técnica clave en el procesamiento de lenguaje natural.
Embedding: [ 0.01676631  0.02484792 -0.05824441 -0.01149719 -0.06505692]...

Frase: ¿Cómo se generan los embeddings?
Embedding: [ 0.00969372 -0.09212597  0.01370841  0.00419837  0.00237616]...

Frase: en que consisten los embeddings y lod transformers
Embedding: [-0.07904124 -0.04865225  0.00054112 -0.08442471  0.01466048]...

Frase: La inteligencia artificial es una tecnica transformadora
Embedding: [-0.0835342   0.01540011 -0.057212   -0.07926246 -0.05903137]...



In [22]:
embeddings[2]

array([ 9.69372317e-03, -9.21259746e-02,  1.37084080e-02,  4.19836957e-03,
        2.37616268e-03,  6.95533156e-02, -2.50207819e-02, -1.87175926e-02,
        3.62586789e-02, -5.01222946e-02,  5.18756807e-02, -1.69165898e-02,
        4.76766983e-03,  3.06400303e-02,  1.94672979e-02,  4.29092944e-02,
       -1.19530093e-02,  5.73895462e-02, -8.13359302e-03,  4.25100736e-02,
        5.53366020e-02,  1.44909350e-02, -2.78168861e-02,  3.14365141e-02,
        1.65497288e-02, -6.91203624e-02, -4.26088367e-03,  5.03181070e-02,
        5.42864092e-02, -9.79611576e-02,  2.25144401e-02,  3.96615677e-02,
       -6.01640670e-03,  5.00718914e-02,  5.86461974e-03,  5.95497340e-02,
        3.59098874e-02, -3.22040319e-02, -6.50166571e-02,  1.94177800e-03,
       -6.80586696e-02,  5.99150360e-02, -1.27734104e-02,  1.86579209e-02,
        3.96977998e-02, -1.14578307e-01, -3.15461755e-02,  5.40043926e-04,
       -8.87479633e-02, -1.08315069e-02, -9.27379206e-02, -5.06190099e-02,
       -3.71532664e-02,  

In [24]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
similitudes = cosine_similarity(embeddings)
# Mostrar los resultados
print("Matriz de similitud del coseno:")
print(similitudes)

# Interpretar similitudes para pares específicos
print("\nSimilitud entre la frase 1 y 2:", similitudes[0][1])
print("Similitud entre la frase 1 y 5:", similitudes[0][4])
print("Similitud entre la frase 2 y 5:", similitudes[1][4])
print("Similitud entre la frase 3 y 4:", similitudes[2][3])

Matriz de similitud del coseno:
[[1.0000001  0.47234815 0.38231775 0.39474615 0.80503994]
 [0.47234815 0.99999964 0.40248802 0.25172287 0.44661933]
 [0.38231775 0.40248802 1.0000002  0.6916104  0.31252074]
 [0.39474615 0.25172287 0.6916104  1.0000004  0.43628487]
 [0.80503994 0.44661933 0.31252074 0.43628487 1.0000005 ]]

Similitud entre la frase 1 y 2: 0.47234815
Similitud entre la frase 1 y 5: 0.80503994
Similitud entre la frase 2 y 5: 0.44661933
Similitud entre la frase 3 y 4: 0.6916104
